// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasswordManager.Infrastructure;

#nullable disable

namespace PasswordManager.Infrastructure.Migrations
{
    [DbContext(typeof(PasswordManagerDbContext))]
    partial class PasswordManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("PasswordManager.Core.EmailAddressPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WebAddressPasswords");
                });

            modelBuilder.Entity("PasswordManager.Core.WebLinkPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WebLinkPasswords");
                });

            modelBuilder.Entity("PasswordManager.Core.EmailAddressPassword", b =>
                {
                    b.OwnsOne("PasswordManager.Core.EmailAddress", "EmailAddress", b1 =>
                        {
                            b1.Property<int>("EmailAddressPasswordId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("EmailAddressPasswordId");

                            b1.ToTable("WebAddressPasswords");

                            b1.WithOwner()
                                .HasForeignKey("EmailAddressPasswordId");
                        });

                    b.OwnsOne("PasswordManager.Core.Password", "Password", b1 =>
                        {
                            b1.Property<int>("EmailAddressPasswordId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("EmailAddressPasswordId");

                            b1.ToTable("WebAddressPasswords");

                            b1.WithOwner()
                                .HasForeignKey("EmailAddressPasswordId");
                        });

                    b.Navigation("EmailAddress")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("PasswordManager.Core.WebLinkPassword", b =>
                {
                    b.OwnsOne("PasswordManager.Core.WebLink", "WebLink", b1 =>
                        {
                            b1.Property<int>("WebLinkPasswordId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("WebLinkPasswordId");

                            b1.ToTable("WebLinkPasswords");

                            b1.WithOwner()
                                .HasForeignKey("WebLinkPasswordId");
                        });

                    b.OwnsOne("PasswordManager.Core.Password", "Password", b1 =>
                        {
                            b1.Property<int>("WebLinkPasswordId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("WebLinkPasswordId");

                            b1.ToTable("WebLinkPasswords");

                            b1.WithOwner()
                                .HasForeignKey("WebLinkPasswordId");
                        });

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("WebLink")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
